name: Tasker

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * MON"

jobs:
  get_rows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Curl data from API
        run: |
          curl -s ${{ secrets.API_ROUTE }} > api_data.json
          echo "var data = $(jq -c .contests api_data.json);" > output.js
          echo  $GITHUB_TOKEN

      - name: Commit files
        run: | 
          git config --local user.email "manan.bansal.1806@gmail.com"
          git config --local user.name "mananbansal2002"
          git add output.js
          git commit -m "Update output.js with JSON data"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
